version: '3.7'

services:
  nginx:
    container_name: nginx
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'

  vue:
    container_name: vue
    build: 
      context: ./vue
      dockerfile: Dockerfile
    ports:
      - '8081:8080'